### ISSUE TITLE
Add _legacyAttrBehavior to can-map@4.0

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-map#114]
Apply this commit to 4.0: https://github.com/canjs/can-map/commit/6c701bd0adfb82b36c4c2a6baea18bc161afebe8#commitcomment-30032586

cc @ivospinheiro

**Comment by ivospinheiro** [comment]
@justinbmeyer I have tried to apply the commit to can-map@4. Please check pull request #115

**Comment by ivospinheiro** [comment]
@justinbmeyer, I think this issue can be closed?
