### ISSUE TITLE
Cannot call .attr(Object) if can-map contains a DefineMap

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-map#18]
Ref: https://jsbin.com/zorucesehu/1/edit?html,js,output

In the `setAttrs` case for can-maps, DefineMaps pass the `types.isMapLike(curVal) ` test, because DefineMap overwrites the function to return true, but can-maps expect all objects that pass `types.isMapLike` to implement `.attr()`, which DefineMap does not do.

Note that this does not fail in the case where `.attr(String, Any)` is called, because the DefineMap is wholesale replaced with a can-map. https://jsbin.com/misaqiroda/1/edit?html,js,output

A similar set of failures occurs when can-map-define is used, but in this case the DefineMap type is preserved in the `.attr(String, Any)` case:  https://jsbin.com/vaxetolora/1/edit?html,js,output

Should DefineMaps implement .attr? Or should we have some other way of recursively descending into set cases for map-likes?

**Comment by justinbmeyer** [comment]
Fixed in https://justinbmeyer.jsbin.com/rawigag/edit?html,js,output
