### ISSUE TITLE
observeReader.write doesn't support writing properties containing `.`s to maps

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-map#65]
@phillipskevin commented on [Fri Mar 31 2017](https://github.com/canjs/can-observation/issues/75)

`Map`s have special rules for writing [properties with dots in the their names](http://canjs.com/doc/can-map.prototype.attr.html#Propertieswithdotsintheirname).

I think this needs to be handled here: https://github.com/canjs/can-observation/blob/master/reader/reader.js#L196

so that it does something like this
```
if (prop.indexOf('.') === -1) {
        base.attr(prop, newVal);
} else {
        base.attr({ [prop]: newVal });
}
```

---

@justinbmeyer commented on [Sun Apr 02 2017](https://github.com/canjs/can-observation/issues/75#issuecomment-291015545)

does escaping work? `prop\.name`?

---

@phillipskevin commented on [Mon Apr 03 2017](https://github.com/canjs/can-observation/issues/75#issuecomment-291128396)

No, not yet. It will work with https://github.com/canjs/can-observation/pull/76. You can double check that the escaping is correct in [this test](https://github.com/canjs/can-observation/pull/76/files#diff-c2f5c2e9723bf79deb862a5b7b93c8a4R143).

---

@justinbmeyer commented on [Tue Apr 18 2017](https://github.com/canjs/can-observation/issues/75#issuecomment-295033606)

The solution to this is that `canReflect.setKeyValue` should be made to handle this right for can-maps.

**Comment by phillipskevin** [comment]
This is related to https://github.com/canjs/can-stache/issues/173.

**Comment by James0x57** [comment]
Hey @bmomberger-bitovi,

We got a lot of the dot bracket stuff working now. I don't fully understand what's going on in this issue but I was told that stuff is related.

Here are some 2-way-binding bracket+dot syntax tests I wrote that are newly passing (as of a few min ago):
https://github.com/canjs/can-stache-bindings/pull/290/files

And some more tests here for normal stache template stuff:
https://github.com/canjs/can-stache/commit/81073f9a0e38a5f885e6efd97ff6242ed204fc9c#diff-e321a00b715070a85ad31c6249bba0cbR5825

Dunno if any of it is a help, but if I can clarify anything, hit me up! 🍻

**Comment by bmomberger-bitovi** [comment]
Seeing as how all the dependent stuff has been merged and we can used dotted properties with bracket notation in can-stache, is this done?

**Comment by phillipskevin** [comment]
This is working now in `can-stache` because `.`s are being escaped: https://github.com/canjs/can-stache/blob/8005a640a50ac7a15cf0410c48e417c6a97dcdfa/src/expression.js#L52. We should handle this in the `setKeyValue` implementations in `can-map` and `can-define/map/map` so that this special casing does not have to happen in `stache`.
